import { useMemo, useState } from "react";
import { useLocation } from "wouter";
import { toast } from "sonner";
import {
  ArrowRight, ArrowUpRight, BarChart3, Box, Check, ChevronDown, ChevronRight,
  CircleHelp, Globe2, Layers3, Menu, Palette, Play, Plus, Search, ShieldCheck,
  ShoppingBag, Sparkles, Store, Truck, Users, X, Zap,
} from "lucide-react";
import { featureData, navItems, planData, storeDemos, templates } from "../data";

const iconMap = { box: Box, chart: BarChart3, palette: Palette, globe: Globe2, users: Users, shield: ShieldCheck, truck: Truck, sparkles: Sparkles } as const;

function Brand({ light = false }: { light?: boolean }) {
  return <a href="/" className={`font-display text-[19px] font-bold tracking-[-0.06em] ${light ? "text-white" : "text-[#141714]"}`} aria-label="HOMSTEG início">HOMSTEG<span className="text-[#b7e93f]">.</span></a>;
}

function Button({ children, variant = "dark", onClick, className = "", type = "button" }: { children: React.ReactNode; variant?: "dark" | "lime" | "ghost" | "outline"; onClick?: () => void; className?: string; type?: "button" | "submit" }) {
  const styles = {
    dark: "bg-[#141714] text-white hover:bg-[#2a3029]",
    lime: "bg-[#c8ff4a] text-[#14200f] hover:bg-[#b8ed3b]",
    ghost: "text-[#5f6a60] hover:text-[#141714]",
    outline: "border border-[#d4ddd1] bg-white text-[#263027] hover:border-[#9cad99]",
  };
  return <button type={type} onClick={onClick} className={`button inline-flex items-center justify-center gap-2 rounded-full px-5 py-3 text-[13px] font-semibold ${styles[variant]} ${className}`}>{children}</button>;
}

function SectionLabel({ children }: { children: React.ReactNode }) {
  return <div className="mb-4 flex items-center gap-2 text-[11px] font-bold uppercase tracking-[0.18em] text-[#7a877b]"><span className="h-1.5 w-1.5 rounded-full bg-[#b9ec42]" />{children}</div>;
}

function DashboardPreview() {
  return <div className="relative mx-auto w-full max-w-[590px] lg:ml-auto">
    <div className="absolute -right-2 top-8 z-0 h-64 w-64 rounded-full bg-[#dfead6] blur-3xl" />
    <div className="relative z-10 overflow-hidden rounded-[22px] border border-[#cbd8c7] bg-white shadow-[0_28px_75px_rgba(40,62,37,.18)]">
      <div className="flex h-11 items-center justify-between border-b border-[#edf1eb] px-4">
        <div className="flex items-center gap-2"><span className="grid h-6 w-6 place-items-center rounded-[7px] bg-[#141714] text-[10px] font-bold text-[#c8ff4a]">H</span><span className="text-[11px] font-bold tracking-tight">Atelier Nova</span></div>
        <div className="flex items-center gap-3 text-[#839084]"><Search size={13} /><BellDot /><span className="h-6 w-6 rounded-full bg-[#e6eee2]" /></div>
      </div>
      <div className="flex min-h-[340px]">
        <div className="hidden w-[125px] shrink-0 border-r border-[#edf1eb] bg-[#fbfcfa] p-3 sm:block">
          <div className="mb-6 text-[8px] font-bold uppercase tracking-[.18em] text-[#a1aca1]">Workspace</div>
          <div className="space-y-1 text-[10px] font-semibold"><SideRow active icon="⌂" label="Início" /><SideRow icon="□" label="Produtos" /><SideRow icon="⌘" label="Design" /><SideRow icon="↗" label="Domínio" /><SideRow icon="⚙" label="Configurações" /></div>
          <div className="mt-8 rounded-[10px] bg-[#eff6dc] p-2.5"><div className="mb-1 text-[8px] font-bold text-[#58702e]">PLANO BUSINESS</div><div className="mb-2 text-[8px] leading-3 text-[#718163]">86% dos produtos usados</div><div className="h-1 rounded-full bg-[#d8e8b7]"><div className="h-1 w-[86%] rounded-full bg-[#8cc52b]" /></div></div>
        </div>
        <div className="min-w-0 flex-1 bg-[#f8faf7] p-4 sm:p-5">
          <div className="mb-4 flex items-start justify-between"><div><div className="text-[10px] text-[#899589]">Terça-feira, 08 Setembro 2026</div><h3 className="mt-1 font-display text-[19px] font-semibold tracking-[-.04em]">Bom dia, Amélia.</h3></div><span className="hidden rounded-full bg-white px-3 py-2 text-[9px] font-semibold text-[#566256] shadow-sm sm:block">Ver loja <ArrowUpRight className="ml-1 inline" size={10} /></span></div>
          <div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><Metric label="Receita total" value="48.920" change="+18,4%" /><Metric label="Encomendas" value="186" change="+12,8%" /><Metric label="Clientes" value="1.284" change="+8,2%" /><Metric label="Conversão" value="3,84%" change="+0,6%" /></div>
          <div className="mt-3 grid gap-3 sm:grid-cols-[1.35fr_1fr]">
            <div className="rounded-[12px] border border-[#e5ebe2] bg-white p-3"><div className="mb-2 flex justify-between text-[9px] font-bold"><span>Vendas por período</span><span className="font-normal text-[#92a092]">Últimos 30 dias⌄</span></div><div className="relative h-[112px] overflow-hidden"><div className="absolute inset-x-0 top-3 border-t border-dashed border-[#e6ece4]" /><div className="absolute inset-x-0 top-14 border-t border-dashed border-[#e6ece4]" /><div className="absolute inset-x-0 bottom-4 border-t border-[#e6ece4]" /><svg className="absolute inset-0 h-full w-full" viewBox="0 0 350 120" preserveAspectRatio="none"><path d="M0 98 C25 95 33 72 58 80 S93 105 116 73 S143 61 165 68 S192 44 214 55 S242 24 259 43 S287 51 306 24 S334 31 350 10 L350 120 L0 120Z" fill="#eff8d7" /><path d="M0 98 C25 95 33 72 58 80 S93 105 116 73 S143 61 165 68 S192 44 214 55 S242 24 259 43 S287 51 306 24 S334 31 350 10" fill="none" stroke="#86b83a" strokeWidth="2.5" /></svg><div className="absolute bottom-0 flex w-full justify-between text-[8px] text-[#9aa69a]"><span>01 Set</span><span>08 Set</span><span>15 Set</span><span>22 Set</span><span>30 Set</span></div></div></div>
            <div className="rounded-[12px] border border-[#e5ebe2] bg-white p-3"><div className="mb-3 flex justify-between text-[9px] font-bold"><span>Produtos mais vendidos</span><span className="text-[#86a33e]">Ver tudo</span></div><MiniProduct name="Cloud Knit" value="24 vendas" color="bg-[#e5d6c8]" /><MiniProduct name="Everyday Tote" value="18 vendas" color="bg-[#d5e2ee]" /><MiniProduct name="Sculptural Candle" value="15 vendas" color="bg-[#ecebcf]" /></div>
          </div>
          <div className="mt-3 rounded-[12px] border border-[#e5ebe2] bg-white p-3"><div className="mb-3 flex items-center justify-between"><span className="text-[9px] font-bold">Encomendas recentes</span><span className="text-[9px] font-semibold text-[#86a33e]">Ver encomendas <ArrowRight className="ml-0.5 inline" size={9} /></span></div><div className="grid grid-cols-[1.2fr_1fr_.7fr_.6fr] gap-2 text-[8px] text-[#98a398]"><span>ID</span><span>Cliente</span><span>Estado</span><span className="text-right">Total</span><span className="font-semibold text-[#425242]">#HST-0924</span><span>Amélia Sitoe</span><span className="text-[#6d9b3a]">Pago</span><span className="text-right font-semibold text-[#425242]">3.240 MZN</span></div></div>
        </div>
      </div>
    </div>
    <div className="absolute -bottom-7 -left-5 z-20 hidden w-48 rounded-[14px] border border-[#dbe6d8] bg-white p-3 shadow-[0_20px_40px_rgba(40,62,37,.14)] sm:block"><div className="mb-2 flex items-center justify-between"><span className="text-[9px] font-bold">Loja online</span><span className="flex items-center gap-1 text-[8px] font-semibold text-[#6e9d30]"><span className="h-1.5 w-1.5 rounded-full bg-[#9bd63d]" /> Activa</span></div><div className="h-16 rounded-[8px] bg-[url('https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=500&q=80')] bg-cover bg-center" /><div className="mt-2 flex items-center justify-between text-[8px] text-[#7b887c]"><span>ateliernova.homsteg.com</span><ArrowUpRight size={10} /></div></div>
  </div>;
}

function BellDot() { return <div className="relative"><span className="text-[13px]">◔</span><span className="absolute -right-1 -top-1 h-1.5 w-1.5 rounded-full bg-[#b9ec42]" /></div>; }
function SideRow({ active, icon, label }: { active?: boolean; icon: string; label: string }) { return <div className={`flex items-center gap-2 rounded-[7px] px-2 py-1.5 ${active ? "bg-[#eaf6cf] text-[#4f682d]" : "text-[#879287]"}`}><span className="w-3 text-center text-[12px]">{icon}</span>{label}</div>; }
function Metric({ label, value, change }: { label: string; value: string; change: string }) { return <div className="rounded-[10px] border border-[#e5ebe2] bg-white p-2.5"><div className="text-[8px] text-[#899589]">{label}</div><div className="mt-1 font-display text-[15px] font-semibold tracking-[-.05em]">{value}<span className="ml-1 text-[8px] font-medium text-[#76a13b]">{change}</span></div></div>; }
function MiniProduct({ name, value, color }: { name: string; value: string; color: string }) { return <div className="mb-2 flex items-center gap-2"><div className={`h-7 w-7 rounded-[6px] ${color}`} /><div className="flex-1 text-[9px] font-semibold"><div>{name}</div><div className="mt-0.5 text-[8px] font-normal text-[#98a398]">{value}</div></div><span className="text-[9px] font-semibold">↗</span></div>; }

export default function Home() {
  const [, navigate] = useLocation();
  const [mobileOpen, setMobileOpen] = useState(false);
  const [storeFilter, setStoreFilter] = useState("Todos");
  const [faqOpen, setFaqOpen] = useState<number | null>(0);
  const filters = ["Todos", "Fashion", "Beauty", "Home", "Technology", "Food"];
  const visibleStores = useMemo(() => storeFilter === "Todos" ? storeDemos.slice(0, 6) : storeDemos.filter((store) => store.category === storeFilter), [storeFilter]);
  const start = () => navigate("/app");

  return <div className="min-h-screen overflow-x-hidden bg-[#f6f8f4] text-[#141714]">
    <header className="sticky top-0 z-50 border-b border-[#e4ebe1]/80 bg-[#f6f8f4]/90 backdrop-blur-xl"><div className="container flex h-[72px] items-center justify-between"><Brand /><nav className="hidden items-center gap-7 lg:flex">{navItems.map((item) => <a key={item.label} href={item.href} className="text-[12px] font-medium text-[#718071] transition-colors hover:text-[#141714]">{item.label}</a>)}</nav><div className="hidden items-center gap-2 sm:flex"><Button variant="ghost" className="px-3" onClick={start}>Entrar</Button><Button variant="dark" onClick={start}>Criar loja <ArrowUpRight size={14} /></Button></div><button onClick={() => setMobileOpen(!mobileOpen)} className="grid h-10 w-10 place-items-center rounded-full border border-[#dbe4d8] lg:hidden" aria-label="Abrir menu">{mobileOpen ? <X size={18} /> : <Menu size={18} />}</button></div>{mobileOpen && <div className="container border-t border-[#e4ebe1] py-4 lg:hidden"><div className="grid gap-1">{navItems.map((item) => <a onClick={() => setMobileOpen(false)} key={item.label} href={item.href} className="rounded-lg px-2 py-2.5 text-sm text-[#647064]">{item.label}</a>)}<Button variant="dark" className="mt-2 w-full" onClick={start}>Criar loja <ArrowUpRight size={14} /></Button></div></div>}</header>

    <main>
      <section id="inicio" className="soft-noise grid-paper relative overflow-hidden border-b border-[#e4ebe1]"><div className="container grid min-h-[670px] items-center gap-16 py-20 lg:grid-cols-[.88fr_1.12fr] lg:py-24"><div className="reveal max-w-[530px]"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#dce7d7] bg-white/70 px-3 py-1.5 text-[11px] font-semibold text-[#667566]"><span className="h-1.5 w-1.5 rounded-full bg-[#a8dc3c]" />Feito para vender com clareza <ArrowUpRight size={12} /></div><h1 className="text-balance font-display text-[clamp(3.3rem,6vw,5.9rem)] font-semibold leading-[.94] tracking-[-.075em]">Crie a sua loja online.<br /><span className="text-[#92b63d]">Venda. Cresça.</span><br />Controle tudo.</h1><p className="mt-7 max-w-[440px] text-[16px] leading-7 text-[#6d786d]">A plataforma elegante para lançar, personalizar e gerir a sua loja online — dos primeiros produtos ao próximo milhão.</p><div className="mt-9 flex flex-wrap gap-3"><Button variant="dark" onClick={start}>Começar gratuitamente <ArrowRight size={15} /></Button><Button variant="outline" onClick={() => document.getElementById("lojas")?.scrollIntoView({ behavior: "smooth" })}><Play size={14} className="fill-current" /> Explorar lojas</Button></div><div className="mt-10 flex items-center gap-4 text-[11px] text-[#7b887b]"><div className="flex -space-x-2"><span className="grid h-7 w-7 place-items-center rounded-full border-2 border-[#f6f8f4] bg-[#d6e6c7] text-[9px] font-bold">AS</span><span className="grid h-7 w-7 place-items-center rounded-full border-2 border-[#f6f8f4] bg-[#f1d2b8] text-[9px] font-bold">MN</span><span className="grid h-7 w-7 place-items-center rounded-full border-2 border-[#f6f8f4] bg-[#d5dded] text-[9px] font-bold">JT</span></div><span><b className="text-[#303a31]">+2.400</b> marcas já começaram</span></div></div><div className="reveal reveal-delay-2"><DashboardPreview /></div></div><div className="absolute bottom-5 left-1/2 hidden -translate-x-1/2 items-center gap-2 text-[10px] font-semibold uppercase tracking-[.2em] text-[#8b978b] lg:flex"><span className="h-8 w-px bg-[#b7c4b4]" />Scroll para explorar</div></section>

      <section className="border-b border-[#e4ebe1] bg-white"><div className="container grid gap-6 py-6 sm:grid-cols-4"><div className="flex items-center gap-3 border-b border-[#edf1eb] pb-4 sm:border-b-0 sm:border-r sm:pb-0"><Zap size={17} className="text-[#8ebc31]" /><div><div className="text-[12px] font-bold">Comece em minutos</div><div className="text-[11px] text-[#879287]">Sem código, sem complicar</div></div></div><div className="flex items-center gap-3 border-b border-[#edf1eb] pb-4 sm:border-b-0 sm:border-r sm:pb-0 sm:pl-5"><Globe2 size={17} className="text-[#8ebc31]" /><div><div className="text-[12px] font-bold">Pronto para Moçambique</div><div className="text-[11px] text-[#879287]">MZN, WhatsApp e entregas locais</div></div></div><div className="flex items-center gap-3 border-b border-[#edf1eb] pb-4 sm:border-b-0 sm:border-r sm:pb-0 sm:pl-5"><ShieldCheck size={17} className="text-[#8ebc31]" /><div><div className="text-[12px] font-bold">Seguro por natureza</div><div className="text-[11px] text-[#879287]">Cada loja tem os seus dados</div></div></div><div className="flex items-center gap-3 sm:pl-5"><Users size={17} className="text-[#8ebc31]" /><div><div className="text-[12px] font-bold">Feito para crescer</div><div className="text-[11px] text-[#879287]">Da primeira venda à escala</div></div></div></div></section>

      <section id="lojas" className="container py-24"><div className="mb-10 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><SectionLabel>Inspire-se</SectionLabel><h2 className="max-w-[620px] font-display text-4xl font-semibold tracking-[-.06em] sm:text-5xl">Veja o que pode criar<br /><span className="text-[#91b63c]">com o HOMSTEG.</span></h2></div><p className="max-w-[280px] text-[13px] leading-6 text-[#7b887b]">Lojas demo originais para mostrar o que acontece quando uma boa ideia encontra as ferramentas certas.</p></div><div className="no-scrollbar mb-7 flex gap-2 overflow-x-auto pb-1">{filters.map((filter) => <button key={filter} onClick={() => setStoreFilter(filter)} className={`rounded-full border px-4 py-2 text-[11px] font-semibold transition-colors ${storeFilter === filter ? "border-[#141714] bg-[#141714] text-white" : "border-[#dbe4d8] bg-white text-[#718071] hover:border-[#9dac98]"}`}>{filter}</button>)}</div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{visibleStores.map((store, index) => <a href={`/store/${store.slug}`} key={store.slug} className={`group hover-lift overflow-hidden rounded-[16px] border border-[#e0e8de] bg-white ${index === 0 && storeFilter === "Todos" ? "sm:col-span-2 lg:col-span-2" : ""}`}><div className={`relative overflow-hidden bg-[#e7eee4] ${index === 0 && storeFilter === "Todos" ? "aspect-[1.65]" : "aspect-[1.24]"}`}><img src={store.image} alt={`${store.name} — ${store.category}`} className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-[1.04]" /><div className="absolute inset-0 bg-gradient-to-t from-black/35 via-transparent to-transparent" /><span className="absolute left-4 top-4 rounded-full bg-white/85 px-2.5 py-1 text-[10px] font-bold text-[#3d483d] backdrop-blur">DEMO STORE</span><span className="absolute bottom-4 left-4 rounded-full px-2.5 py-1 text-[10px] font-bold" style={{ backgroundColor: store.accent }}>{store.tone}</span><span className="absolute bottom-4 right-4 grid h-9 w-9 place-items-center rounded-full bg-white text-[#1a201a] opacity-0 transition-opacity group-hover:opacity-100"><ArrowUpRight size={16} /></span></div><div className="flex items-center justify-between p-4"><div><h3 className="font-display text-[17px] font-semibold tracking-[-.04em]">{store.name}</h3><div className="mt-1 text-[11px] text-[#8a968b]">{store.category} · Template {index % 2 === 0 ? "Editorial" : "Modern"}</div></div><ChevronRight size={16} className="text-[#9cab9d]" /></div></a>)}</div><div className="mt-7 flex justify-center"><Button variant="outline" onClick={() => { setStoreFilter("Todos"); toast.success("A mostrar todas as lojas demo."); }}>Ver todas as lojas <ArrowRight size={14} /></Button></div></section>

      <section id="recursos" className="border-y border-[#e4ebe1] bg-[#eaf1e6]"><div className="container py-24"><div className="grid gap-14 lg:grid-cols-[.72fr_1.28fr]"><div><SectionLabel>Uma plataforma inteira</SectionLabel><h2 className="font-display text-4xl font-semibold leading-[1.02] tracking-[-.06em] sm:text-5xl">Menos ferramentas.<br /><span className="text-[#91b63c]">Mais movimento.</span></h2><p className="mt-6 max-w-[360px] text-[14px] leading-6 text-[#6d796d]">Tudo o que precisa para operar uma loja que parece grande — mesmo quando está a começar.</p><Button variant="dark" className="mt-8" onClick={start}>Explorar o painel <ArrowUpRight size={14} /></Button><div className="mt-12 rounded-[16px] border border-[#d4e0d1] bg-white/70 p-5"><div className="mb-3 flex items-center justify-between"><span className="text-[11px] font-bold">Saúde da sua loja</span><span className="text-[10px] font-bold text-[#6f9d31]">Excelente</span></div><div className="h-2 overflow-hidden rounded-full bg-[#deead8]"><div className="h-full w-[88%] rounded-full bg-[#9ed33a]" /></div><div className="mt-3 flex justify-between text-[10px] text-[#899588]"><span>4 de 5 passos concluídos</span><span>88%</span></div></div></div><div className="grid gap-3 sm:grid-cols-2">{featureData.map((feature, i) => { const Icon = iconMap[feature.icon as keyof typeof iconMap]; return <div key={feature.title} className="hover-lift rounded-[14px] border border-[#dce7d9] bg-white p-5"><div className="mb-9 flex h-9 w-9 items-center justify-center rounded-[10px] bg-[#eff8d7] text-[#719b2e]"><Icon size={17} /></div><h3 className="font-display text-[17px] font-semibold tracking-[-.04em]">{feature.title}</h3><p className="mt-2 text-[12px] leading-5 text-[#7b887b]">{feature.text}</p></div>})}</div></div></div></section>

      <section id="como-funciona" className="container py-24"><div className="grid gap-14 lg:grid-cols-[.55fr_1.45fr]"><div><SectionLabel>Como funciona</SectionLabel><h2 className="font-display text-4xl font-semibold leading-[1.04] tracking-[-.06em] sm:text-5xl">Da ideia à<br /><span className="text-[#91b63c]">primeira venda.</span></h2></div><div className="grid border-t border-[#dce5da] sm:grid-cols-2">{["Crie a sua conta", "Crie a sua loja", "Escolha um template", "Personalize o design", "Adicione produtos", "Configure pagamentos", "Publique", "Comece a vender"].map((step, i) => <div key={step} className="flex gap-4 border-b border-[#dce5da] py-5 sm:nth-[odd]:border-r sm:nth-[odd]:pr-7 sm:nth-[even]:pl-7"><span className="font-display text-[12px] font-semibold text-[#9bbb54]">0{i + 1}</span><div><h3 className="font-display text-[15px] font-semibold tracking-[-.03em]">{step}</h3><p className="mt-1 text-[11px] leading-5 text-[#879287]">{["Um espaço de trabalho só seu, pronto para começar.", "Defina nome, moeda, contacto e a personalidade da marca.", "Escolha uma base bonita e feita para o seu tipo de negócio.", "Cores, tipografia e secções sem tocar em código.", "Importe o catálogo ou crie o primeiro produto em minutos.", "Aceite pagamentos locais, cartão ou pagamento manual.", "Um clique para tornar a sua loja visível ao mundo.", "Acompanhe tudo a partir de um único painel."][i]}</p></div></div>)}</div></div></section>

      <section id="templates" className="border-y border-[#e4ebe1] bg-[#141714] text-white"><div className="container py-24"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><SectionLabel>O começo certo</SectionLabel><h2 className="font-display text-4xl font-semibold tracking-[-.06em] sm:text-5xl">Templates para<br /><span className="text-[#c8ff4a]">cada tipo de negócio.</span></h2></div><p className="max-w-[285px] text-[13px] leading-6 text-[#a1aea1]">Escolha uma direcção visual. Depois, torne-a completamente sua.</p></div><div className="no-scrollbar mt-12 flex gap-5 overflow-x-auto pb-4">{templates.map((template) => <div key={template.name} className="group min-w-[270px] max-w-[300px] flex-1 overflow-hidden rounded-[15px] border border-white/10 bg-white/[.06]"><div className="relative aspect-[1.15] overflow-hidden"><img src={template.image} alt={`${template.name} template`} className="h-full w-full object-cover opacity-85 transition-transform duration-500 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-[#141714] via-transparent to-transparent" /><span className="absolute left-3 top-3 rounded-full bg-[#c8ff4a] px-2.5 py-1 text-[9px] font-bold uppercase tracking-wider text-[#1c2712]">{template.badge}</span><div className="absolute bottom-3 left-3 text-[10px] font-semibold text-white/75">{template.category}</div></div><div className="p-4"><div className="flex items-center justify-between"><h3 className="font-display text-[18px] font-semibold tracking-[-.04em]">{template.name}</h3><button aria-label={`Usar template ${template.name}`} onClick={() => { toast.success(`${template.name} seleccionado`, { description: "Vamos preparar a sua loja." }); navigate("/app/design"); }} className="grid h-8 w-8 place-items-center rounded-full bg-white/10 text-[#c8ff4a] hover:bg-[#c8ff4a] hover:text-[#141714]"><ArrowUpRight size={14} /></button></div><p className="mt-2 text-[11px] leading-5 text-[#a1aea1]">{template.description}</p></div></div>)}</div></div></section>

      <section id="precos" className="container py-24"><div className="mb-12 text-center"><SectionLabel>Planos simples</SectionLabel><h2 className="font-display text-4xl font-semibold tracking-[-.06em] sm:text-5xl">Comece pequeno.<br /><span className="text-[#91b63c]">Pense grande.</span></h2><p className="mx-auto mt-4 max-w-[410px] text-[13px] leading-6 text-[#7b887b]">Sem contratos longos. Faça upgrade quando a sua loja pedir mais espaço.</p></div><div className="grid gap-3 lg:grid-cols-5">{planData.map((plan) => <div key={plan.name} className={`relative flex flex-col rounded-[15px] border p-5 ${plan.featured ? "border-[#9fc83f] bg-[#eff8d7] shadow-[0_12px_30px_rgba(116,153,45,.13)]" : "border-[#e0e8de] bg-white"}`}>{plan.featured && <span className="absolute -top-3 left-5 rounded-full bg-[#b4e542] px-3 py-1 text-[9px] font-bold uppercase tracking-wider text-[#1d2a12]">Mais escolhido</span>}<div className="text-[12px] font-bold">{plan.name}</div><div className="mt-5 flex items-baseline gap-1"><span className="font-display text-3xl font-semibold tracking-[-.07em]">{plan.price}</span><span className="text-[10px] text-[#899589]">MZN/mês</span></div><p className="mt-2 min-h-[36px] text-[11px] leading-5 text-[#7b887b]">{plan.description}</p><div className="my-5 h-px bg-[#e2eadd]" /><ul className="flex-1 space-y-3">{plan.features.map((feature) => <li key={feature} className="flex gap-2 text-[11px] text-[#617061]"><Check size={13} className="mt-0.5 shrink-0 text-[#83ad35]" />{feature}</li>)}</ul><Button variant={plan.featured ? "dark" : "outline"} className="mt-7 w-full !px-2 text-[11px]" onClick={start}>{plan.cta}</Button></div>)}</div></section>

      <section id="faq" className="border-y border-[#e4ebe1] bg-white"><div className="container grid gap-12 py-24 lg:grid-cols-[.65fr_1.35fr]"><div><SectionLabel>Tem dúvidas?</SectionLabel><h2 className="font-display text-4xl font-semibold tracking-[-.06em] sm:text-5xl">Tudo claro<br /><span className="text-[#91b63c]">desde o início.</span></h2><p className="mt-5 max-w-[300px] text-[13px] leading-6 text-[#7b887b]">Se não encontrar a resposta, a nossa equipa está a uma mensagem de distância.</p><Button variant="outline" className="mt-7" onClick={() => toast.success("Mensagem recebida", { description: "A equipa HOMSTEG entrará em contacto." })}>Falar com a equipa <ArrowRight size={14} /></Button></div><div className="divide-y divide-[#e4ebe1] border-t border-[#e4ebe1]">{["Posso começar gratuitamente?", "Preciso de saber programar?", "Como funcionam os pagamentos em MZN?", "Posso usar o meu próprio domínio?", "Os meus dados ficam separados dos outros lojistas?", "Posso mudar de plano mais tarde?"].map((question, index) => <div key={question}><button onClick={() => setFaqOpen(faqOpen === index ? null : index)} className="flex w-full items-center justify-between py-5 text-left"><span className="font-display text-[15px] font-semibold tracking-[-.025em]">{question}</span><span className={`grid h-7 w-7 shrink-0 place-items-center rounded-full border border-[#dce5da] transition-transform ${faqOpen === index ? "rotate-180 bg-[#eff8d7]" : ""}`}><ChevronDown size={14} /></span></button>{faqOpen === index && <p className="-mt-2 max-w-[620px] pb-5 pr-10 text-[12px] leading-6 text-[#7b887b]">{["Sim. O plano Free permite publicar uma loja com até 10 produtos e começar a vender sem compromisso.", "Não. O HOMSTEG foi criado para que possa construir uma loja profissional sem escrever código.", "Pode aceitar pagamentos manuais, WhatsApp e configurar os métodos mais adequados à sua operação.", "Sim. Os planos Starter, Business, Pro e Enterprise suportam domínio personalizado.", "Sim. Cada loja funciona como um tenant isolado, com permissões e dados próprios.", "Sim. Pode fazer upgrade ou downgrade a qualquer momento a partir das Configurações."][index]}</p>}</div>)}</div></div></section>

      <section className="container py-24"><div className="soft-noise relative overflow-hidden rounded-[24px] bg-[#c8ff4a] px-7 py-14 sm:px-14"><div className="absolute -right-16 -top-20 h-64 w-64 rounded-full border-[40px] border-[#b8eb3c]" /><div className="absolute -bottom-20 right-44 h-48 w-48 rounded-full border-[28px] border-[#b8eb3c]" /><div className="relative max-w-[620px]"><SectionLabel>O seu próximo capítulo</SectionLabel><h2 className="font-display text-4xl font-semibold leading-[1.02] tracking-[-.06em] sm:text-6xl">A sua loja merece<br />um sistema à altura.</h2><p className="mt-5 max-w-[430px] text-[14px] leading-6 text-[#4b5d37]">Junte-se a quem está a construir negócios mais bonitos, mais simples e mais preparados para crescer.</p><Button variant="dark" className="mt-8" onClick={start}>Criar a minha loja <ArrowUpRight size={15} /></Button></div></div></section>
    </main>

    <footer className="border-t border-[#e4ebe1] bg-[#eef3ec]"><div className="container py-14"><div className="grid gap-12 sm:grid-cols-[1.5fr_1fr_1fr_1fr] lg:gap-20"><div><Brand /><p className="mt-4 max-w-[240px] text-[12px] leading-5 text-[#7b887b]">A plataforma de comércio para quem quer fazer mais com menos.</p><div className="mt-7 flex h-8 w-8 items-center justify-center rounded-full bg-[#dce9d4] text-[12px] font-bold">in</div></div><FooterCol title="Produto" links={["Recursos", "Preços", "Templates", "Lojas demo"]} /><FooterCol title="Empresa" links={["Sobre o HOMSTEG", "Contacto", "Carreiras", "Parceiros"]} /><FooterCol title="Legal" links={["Termos", "Privacidade", "Cookies", "Segurança"]} /></div><div className="mt-14 flex flex-col justify-between gap-3 border-t border-[#dbe5d8] pt-5 text-[10px] text-[#8a968b] sm:flex-row"><span>© 2026 HOMSTEG, Inc. Feito em Maputo para o mundo.</span><span>Português (PT) · MZN</span></div></div></footer>
  </div>;
}

function FooterCol({ title, links }: { title: string; links: string[] }) { return <div><div className="mb-4 text-[10px] font-bold uppercase tracking-[.16em] text-[#6f7e70]">{title}</div><div className="grid gap-3">{links.map((link) => <a href="#" key={link} className="text-[12px] text-[#7c897d] hover:text-[#141714]">{link}</a>)}</div></div>; }
