import { useMemo, useState } from "react";
import { useLocation, useRoute } from "wouter";
import { toast } from "sonner";
import { ArrowLeft, ArrowRight, Check, Heart, Menu, Plus, Search, ShoppingBag, Sparkles, UserRound, X } from "lucide-react";
import { storeDemos } from "../data";

const catalog = [
  { name: "Cloud Knit", price: "3.200 MZN", image: "https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=700&q=85", tag: "New in" },
  { name: "Everyday Tote", price: "2.450 MZN", image: "https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=700&q=85", tag: "Best seller" },
  { name: "Sculptural Candle", price: "1.890 MZN", image: "https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=700&q=85", tag: "Home" },
  { name: "Desk Light 02", price: "4.890 MZN", image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=700&q=85", tag: "Object" },
  { name: "Sculpted Shirt", price: "2.980 MZN", image: "https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&w=700&q=85", tag: "Edit" },
  { name: "Soft Form Bowl", price: "1.490 MZN", image: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=700&q=85", tag: "Object" },
];
type Item = typeof catalog[number];

export default function Storefront() {
  const [, params] = useRoute("/store/:slug");
  const [, navigate] = useLocation();
  const store = storeDemos.find((item) => item.slug === params?.slug) || storeDemos[0];
  const [cart, setCart] = useState<Item[]>([]);
  const [cartOpen, setCartOpen] = useState(false);
  const [searchOpen, setSearchOpen] = useState(false);
  const [query, setQuery] = useState("");
  const filtered = useMemo(() => catalog.filter((item) => `${item.name} ${item.tag}`.toLowerCase().includes(query.toLowerCase())), [query]);
  const addToCart = (item: Item) => {
    setCart((items) => items.some((current) => current.name === item.name) ? items : [...items, item]);
    setCartOpen(true);
    toast.success("Adicionado ao carrinho", { description: item.name });
  };
  const isFashion = store.category === "Fashion" || store.category === "Luxury";

  return <div className="min-h-screen bg-[#f8f7f3] text-[#1d211d]">
    <div className="border-b border-[#dedfd8] bg-[#ede8d9] px-4 py-2 text-center text-[10px] font-bold uppercase tracking-[.18em] text-[#6e705f]">Envio nacional gratuito em compras acima de 5.000 MZN</div>
    <header className="sticky top-0 z-30 border-b border-[#e3e3dc]/90 bg-[#f8f7f3]/90 backdrop-blur-xl">
      <div className="mx-auto flex h-[76px] max-w-[1240px] items-center justify-between px-5 sm:px-8">
        <button onClick={() => navigate("/")} className="flex items-center gap-2 text-[10px] text-[#898c80] hover:text-[#232821]"><ArrowLeft size={14} /><span className="hidden sm:inline">Voltar ao HOMSTEG</span><span className="sm:hidden">Voltar</span></button>
        <a href={`/store/${store.slug}`} className="absolute left-1/2 -translate-x-1/2 font-display text-[18px] font-semibold tracking-[-.08em]">{store.name.toUpperCase()}</a>
        <div className="flex items-center gap-3">
          <button onClick={() => setSearchOpen(!searchOpen)} aria-label="Pesquisar" className="text-[#667064]"><Search size={17} /></button>
          <button onClick={() => toast.info("Conta de cliente", { description: "O login de cliente estará disponível no próximo passo." })} aria-label="Conta" className="hidden text-[#667064] sm:block"><UserRound size={17} /></button>
          <button onClick={() => setCartOpen(true)} aria-label="Carrinho" className="relative text-[#667064]"><ShoppingBag size={17} />{cart.length > 0 && <span className="absolute -right-2 -top-2 grid h-4 w-4 place-items-center rounded-full bg-[#1d211d] text-[9px] text-white">{cart.length}</span>}</button>
          <button className="text-[#667064] sm:hidden" aria-label="Menu"><Menu size={17} /></button>
        </div>
      </div>
      {searchOpen && <div className="border-t border-[#e3e3dc] bg-white px-5 py-3"><div className="mx-auto flex max-w-[1240px] items-center gap-3"><Search size={15} className="text-[#9ca298]" /><input autoFocus value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Pesquisar na loja..." className="flex-1 bg-transparent text-sm outline-none placeholder:text-[#a4aaa0]" /><button onClick={() => { setQuery(""); setSearchOpen(false); }} aria-label="Fechar pesquisa"><X size={15} className="text-[#899288]" /></button></div></div>}
    </header>

    <main>
      <section className="mx-auto max-w-[1240px] px-5 pt-5 sm:px-8"><div className="relative min-h-[560px] overflow-hidden bg-cover bg-center p-7 sm:p-12" style={{ backgroundImage: `url(${store.image})` }}><div className="absolute inset-0 bg-gradient-to-r from-black/55 via-black/20 to-transparent" /><div className="relative flex min-h-[500px] max-w-[510px] flex-col justify-end text-white"><div className="mb-4 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.25em] text-white/70"><Sparkles size={12} />{isFashion ? "New collection · SS26" : `${store.category} · Curated selection`}</div><h1 className="font-display text-6xl font-semibold leading-[.88] tracking-[-.08em] sm:text-8xl">{isFashion ? <>The shape<br />of now.</> : <>Made for<br />your everyday.</>}</h1><p className="mt-6 max-w-[330px] text-[13px] leading-6 text-white/80">Objectos com intenção, seleccionados para acompanhar o ritmo de todos os dias.</p><button onClick={() => document.getElementById("products")?.scrollIntoView({ behavior: "smooth" })} className="mt-7 flex w-fit items-center gap-2 rounded-full px-5 py-3 text-[11px] font-bold" style={{ backgroundColor: store.accent, color: "#1d211d" }}>Explorar coleção <ArrowRight size={14} /></button></div><div className="absolute bottom-6 right-7 hidden text-right text-[10px] uppercase tracking-[.2em] text-white/65 sm:block">{store.name}<br />Maputo · Moçambique</div></div></section>
      <section className="mx-auto max-w-[1240px] px-5 py-14 sm:px-8"><div className="grid gap-5 border-y border-[#dedfd8] py-5 sm:grid-cols-3"><div><div className="mb-2 text-[10px] font-bold uppercase tracking-[.16em] text-[#9a9e94]">01 · Material</div><div className="font-display text-[15px] font-semibold tracking-[-.03em]">Feito para durar.</div></div><div><div className="mb-2 text-[10px] font-bold uppercase tracking-[.16em] text-[#9a9e94]">02 · Processo</div><div className="font-display text-[15px] font-semibold tracking-[-.03em]">Pensado com calma.</div></div><div><div className="mb-2 text-[10px] font-bold uppercase tracking-[.16em] text-[#9a9e94]">03 · Entrega</div><div className="font-display text-[15px] font-semibold tracking-[-.03em]">Da nossa porta à sua.</div></div></div></section>
      <section id="products" className="mx-auto max-w-[1240px] px-5 pb-24 sm:px-8"><div className="mb-8 flex items-end justify-between"><div><div className="mb-3 text-[10px] font-bold uppercase tracking-[.2em] text-[#969d91]">A selecção</div><h2 className="font-display text-4xl font-semibold tracking-[-.07em]">Featured edit<span className="text-[#a0bd5b]">.</span></h2></div><button onClick={() => toast.info("Todas as categorias", { description: "A mostrar a coleção completa." })} className="hidden items-center gap-2 text-[11px] font-semibold text-[#6f786c] sm:flex">Ver tudo <ArrowRight size={13} /></button></div><div className="grid gap-x-4 gap-y-9 sm:grid-cols-2 lg:grid-cols-3">{filtered.map((item) => <article key={item.name} className="group"><div className="relative aspect-[.88] w-full overflow-hidden bg-[#ece9e0]"><button onClick={() => addToCart(item)} className="block h-full w-full text-left"><img src={item.image} alt={item.name} className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-[1.035]" /></button><div className="absolute inset-x-0 bottom-0 flex translate-y-full items-center justify-center bg-[#1d211d]/90 py-3 text-[11px] font-semibold text-white transition-transform duration-300 group-hover:translate-y-0" onClick={() => addToCart(item)}>Adicionar ao carrinho <Plus className="ml-1 text-[#c8ff4a]" size={13} /></div><span className="absolute left-3 top-3 rounded-full bg-white/80 px-2.5 py-1 text-[9px] font-bold uppercase tracking-wider backdrop-blur">{item.tag}</span><button aria-label={`Adicionar ${item.name} aos favoritos`} onClick={() => toast.success("Adicionado aos favoritos")} className="absolute right-3 top-3 grid h-8 w-8 place-items-center rounded-full bg-white/80 text-[#667064] backdrop-blur"><Heart size={14} /></button></div><div className="mt-3 flex items-start justify-between"><div><h3 className="font-display text-[15px] font-semibold tracking-[-.03em]">{item.name}</h3><p className="mt-1 text-[11px] text-[#8c9388]">Made in small batches</p></div><span className="text-[12px] font-semibold">{item.price}</span></div></article>)}</div>{filtered.length === 0 && <div className="border-y border-[#dedfd8] py-16 text-center"><Search className="mx-auto mb-3 text-[#a4aaa0]" size={24} /><p className="font-display text-lg font-semibold">Não encontramos resultados.</p><p className="mt-1 text-[12px] text-[#8c9388]">Tente pesquisar por outro termo.</p></div>}</section>
      <section className="bg-[#e8e3d7] px-5 py-20 text-center"><div className="mx-auto max-w-[560px]"><div className="mb-4 text-[10px] font-bold uppercase tracking-[.2em] text-[#888c7d]">Journal</div><h2 className="font-display text-4xl font-semibold leading-[.98] tracking-[-.07em] sm:text-6xl">Small choices.<br />Long stories.</h2><p className="mx-auto mt-5 max-w-[360px] text-[13px] leading-6 text-[#73786c]">Porque o melhor objecto não é o que chama mais atenção. É o que fica.</p><button onClick={() => toast.info("Journal", { description: "Em breve, histórias da comunidade Atelier Nova." })} className="mt-7 rounded-full border border-[#aaa997] px-5 py-3 text-[11px] font-bold">Ler o journal <ArrowRight className="ml-1 inline" size={13} /></button></div></section>
    </main>
    <footer className="mx-auto flex max-w-[1240px] flex-col justify-between gap-5 px-5 py-8 text-[10px] text-[#8c9388] sm:flex-row sm:px-8"><span>© 2026 {store.name}. Uma demo HOMSTEG.</span><div className="flex gap-5"><span>Instagram</span><span>Shipping & returns</span><span>Contact</span></div></footer>
    {cartOpen && <div className="fixed inset-0 z-50 bg-black/20" onClick={() => setCartOpen(false)}><aside onClick={(e) => e.stopPropagation()} className="absolute right-0 top-0 flex h-full w-full max-w-[400px] flex-col bg-white p-6 shadow-2xl"><div className="flex items-center justify-between border-b border-[#e4e6df] pb-5"><div><div className="text-[10px] font-bold uppercase tracking-[.18em] text-[#9aa298]">A sua selecção</div><h2 className="mt-1 font-display text-2xl font-semibold tracking-[-.06em]">Carrinho <span className="text-[#9cba55]">({cart.length})</span></h2></div><button onClick={() => setCartOpen(false)} aria-label="Fechar carrinho"><X size={18} /></button></div>{cart.length ? <><div className="flex-1 divide-y divide-[#edf0e9] overflow-y-auto py-2">{cart.map((item) => <div key={item.name} className="flex gap-3 py-4"><img src={item.image} alt="" className="h-20 w-20 object-cover" /><div className="flex-1"><div className="font-display text-[13px] font-semibold">{item.name}</div><div className="mt-1 text-[11px] text-[#8c9388]">1 unidade</div><div className="mt-3 text-[12px] font-semibold">{item.price}</div></div><button onClick={() => setCart((items) => items.filter((current) => current.name !== item.name))} className="self-start text-[#a0a79d]" aria-label={`Remover ${item.name}`}><X size={14} /></button></div>)}</div><div className="border-t border-[#e4e6df] pt-5"><div className="mb-4 flex justify-between text-[13px] font-semibold"><span>Subtotal</span><span>{cart.reduce((total, item) => total + Number(item.price.replace(/[^0-9]/g, "")), 0).toLocaleString("pt-PT")} MZN</span></div><button onClick={() => toast.success("Checkout iniciado", { description: "O próximo passo é inserir os seus dados de entrega." })} className="w-full rounded-full bg-[#1d211d] px-5 py-3.5 text-[12px] font-bold text-white">Continuar para checkout <ArrowRight className="ml-1 inline" size={14} /></button><div className="mt-3 flex items-center justify-center gap-1 text-[10px] text-[#8e978d]"><Check size={12} className="text-[#88aa3c" />Pagamento seguro e checkout local</div></div></> : <div className="grid flex-1 place-items-center text-center"><div><ShoppingBag className="mx-auto mb-3 text-[#bbc3b8]" size={28} /><div className="font-display text-lg font-semibold">O carrinho está vazio.</div><p className="mt-1 text-[11px] text-[#90998f]">Adicione algo bonito para começar.</p><button onClick={() => setCartOpen(false)} className="mt-5 rounded-full bg-[#1d211d] px-5 py-3 text-[11px] font-bold text-white">Explorar produtos</button></div></div>}</aside></div>}
  </div>;
}
